---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gdyeksti/public_html/
    - export CRMPATH=/home/gdyeksti/crm/
    - /bin/cp -R * 
    - /bin/cp -R * 
    - /bin/touch /home/gdyeksti/crm/tmp/restart.txt
